# permissions for end users to edit exporterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: exporterconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: traefik-external-config
    app.kubernetes.io/part-of: traefik-external-config
    app.kubernetes.io/managed-by: kustomize
  name: exporterconfig-editor-role
rules:
- apiGroups:
  - networking.stiil.dk
  resources:
  - exporterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.stiil.dk
  resources:
  - exporterconfigs/status
  verbs:
  - get
