---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - networking.stiil.dk
  resources:
  - exporterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.stiil.dk
  resources:
  - exporterconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - networking.stiil.dk
  resources:
  - exporterconfigs/status
  verbs:
  - get
  - patch
  - update
